import{css as l,keyframes as f}from"https://assets.acdn.no/pkg/@amedia/brick-tokens/v5/brick-tokens.js";var h=f({"0%":{transform:"scale(0.7)",boxShadow:"0 0 0 0 $$pulseColor70"},"70%":{transform:"scale(1)",boxShadow:"0 0 0 8px $$pulseColor0"},"100%":{transform:"scale(0.7)",boxShadow:"0 0 0 0 $$pulseColor0"}}),m={variants:{iconId:{"pill-breaking":{$$pulseColor70:"$colors$pillNonePulseStartBg",$$pulseColor0:"$colors$pillNonePulseEndBg",fill:"$pillNonePulseBg",borderRadius:"50%",animation:`${h} 2s infinite`,display:"inline-flex","@media (prefers-reduced-motion)":{animation:"none"}},inverted:{true:{},false:{}}}},defaultVariants:{iconId:""}},c=l({display:"inline-flex",...m}),o=l({display:"inline-flex"});import{themeList as $}from"https://assets.acdn.no/pkg/@amedia/brick-tokens/v5/brick-tokens.js";var n=e=>$.includes(e)?e:"alfa";var x=e=>e?'role="graphics-symbol"':'aria-hidden="true"';function s(e){let{iconText:i,iconId:t,iconTheme:a}=e,p="/api/css-config/v1/brick",d=i?`<title style="display: inline;">${i}</title>`:"",u=a&&t?`<use href="${p}/${a}/icons.svg#${t}" />`:"";return`
      <div class="svg-wrap ${c({iconId:t})}">
        <svg ${x(i)} width="32" height="32">
          ${d}
          ${u}
        </svg>
      </div>
      `}function g(e){let i=n(e.iconTheme),t=s({...e,iconTheme:i});return`<brick-icon rendered="true" iconid="${e.iconId}" class="${o}">${t}</brick-icon>`}var r=class extends HTMLElement{constructor(t){super();this.brickIconData=t}async connectedCallback(){this.setData(),this.render()}setData(){this.brickIconData={iconText:this.getAttribute("iconText")||"",iconTheme:n(this.getAttribute("icontheme")),iconId:this.getAttribute("iconId")||""},this.className=o()}render(){this.getAttribute("rendered")!=="true"&&(this.innerHTML=this.template)}get template(){return s(this.brickIconData)}};customElements.get("brick-icon")||customElements.define("brick-icon",r);export{r as BrickIcon,o as iconContainerStyle,c as iconStyle,m as iconVariants,g as renderBrickIcon};
//# sourceMappingURL=brick-icon.js.map
